Global:
  model: PP-LCNet_x2_5
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir: "D:/dl/datasets/zhusu/dataset_classification"
  device: gpu:0
  output: "output/zhusu/text_line_ori_0119_1"

CheckDataset:
  convert: 
    enable: False
    src_dataset_type: null
  split: 
    enable: False
    train_percent: null
    val_percent: null

Train:
  num_classes: 4
  epochs_iters: 75
  batch_size: 64
  learning_rate: 0.0025
  pretrain_weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/PP-LCNet_x2_5_pretrained.pdparams
  warmup_steps: 5
  resume_path: null
  log_interval: 10
  eval_interval: 10
  save_interval: 10

Evaluate:
  weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/PP-LCNet_x2_5_pretrained.pdparams
  log_interval: 1

Export:
  weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/PP-LCNet_x2_5_pretrained.pdparams

Predict:
  batch_size: 1
  model_dir: "output/best_model/inference"
  input: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_image_classification_001.jpg"
  kernel_option:
    run_mode: paddle
