Global:
  model: PP-OCRv6_medium_det
  mode: train
  module: text_det
  dataset_dir: D:/dl/projects/Git/PaddleX-OCR-GUI/merged_datasets/ocr_det_20260602_093318
  device: gpu:0
  output: D:/dl/projects/Git/PaddleX-OCR-GUI/results/det/det_0623_3
CheckDataset:
  convert:
    enable: false
    src_dataset_type: null
  split:
    enable: false
    train_percent: null
    val_percent: null
Train:
  epochs_iters: 75
  batch_size: 4
  learning_rate: 0.0005
  pretrain_weight_path: D:/dl/projects/Git/PaddleX-OCR-GUI/pretrainedpdparams/PP-OCRv6_medium_det_pretrained.pdparams
  resume_path: null
  log_interval: 10
  eval_interval: 10
  save_interval: 10
Evaluate:
  weight_path: output/best_accuracy/best_accuracy.pdparams
  log_interval: 1
Export:
  weight_path: D:/dl/projects/Git/PaddleX-OCR-GUI/results/det_0623/best_accuracy/best_accuracy.pdparams
Predict:
  batch_size: 1
  model_dir: output/best_accuracy/inference
  input: https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_ocr_001.png
  kernel_option:
    run_mode: paddle
