Global:
  model: PP-OCRv6_medium_rec
  mode: train
  dataset_dir: D:/dl/projects/Git/PaddleX-OCR-GUI/merged_datasets/ocr_rec_20260519_1402261
  device: gpu:0
  character_dict_path: D:\dl\projects\Git\PaddleX-custom-3.7\paddlex\repo_manager\repos\PaddleOCR\ppocr\utils\dict\ppocrv6_dict.txt
  output: D:/dl/projects/Git/PaddleX-OCR-GUI/results/rec/rec_0623_4
CheckDataset:
  convert:
    enable: false
    src_dataset_type: null
  split:
    enable: false
    train_percent: null
    val_percent: null
Train:
  epochs_iters: 75
  batch_size: 128
  learning_rate: 0.0001
  pretrain_weight_path: D:/dl/projects/Git/PaddleX-OCR-GUI/pretrainedpdparams/PP-OCRv6_medium_rec_pretrained.pdparams
  resume_path: null
  log_interval: 20
  eval_interval: 10
  save_interval: 10
Evaluate:
  weight_path: output/best_accuracy/best_accuracy.pdparams
  log_interval: 1
Export:
  weight_path: D:/dl/projects/Git/PaddleX-OCR-GUI/results/rec/rec_0623_3/best_accuracy/best_accuracy.pdparams
Predict:
  batch_size: 1
  model_dir: output/best_accuracy/inference
  input: https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_ocr_rec_001.png
  kernel_option:
    run_mode: paddle
